# php image, tag: v7 major, apache, debian stretch
FROM php:7-apache-stretch

# Copy the content of src where it's supposed to be, based on https://hub.docker.com/_/php/ docs.
COPY src/ /var/www/html

# Expose a port. The container will listen on port 80.
EXPOSE 80
